/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * BEGIN C COMPATIBLE FUNCTIONS *
 */

bool check_perms(void);

bool install(const char *package, bool local, bool force);

const char *list(void);

const char *list_available(void);

const char *package_details(const char *package);

bool remove(const char *package, bool force);

bool setup_comet(void);

bool update(const char *package);

void update_all(void);

bool update_cache(void);
